CPPFLAGS = -I..

OBJECTS = BaseCollection.o BaseNotifiee.o Exception.o

all: $(OBJECTS)

clean:
	rm -f $(OBJECTS)

BaseCollection.o: BaseCollection.cpp
BaseNotifiee.o: BaseNotifiee.cpp
Exception.o: Exception.cpp
